CreateConVar("rw_sw_dispenser_health", "950", 8192, "The amount of health of all dispencer")
CreateConVar("rw_sw_dispenser_timer", "2", 8192, "The cooldown between you can take ammo")
CreateConVar("rw_sw_dispenser_ammo_basic_count", "1500", 8192, "The amount of basic ammo")
CreateConVar("rw_sw_dispenser_allammo_multiplier", "3", 8192, "The number of ammo given according to this multiplier of the clipsize")
CreateConVar("rw_sw_dispenser_ammo_crate_number", "5", 8192, "The number of ammo create you can throw with the swep")
CreateConVar("rw_sw_dispenser_heal_amount", "50", 8192, "The amount of heal and armor a dispencer can give")
CreateConVar("rw_sw_dispenser_max_armor", "200", 8192, "The limit of armor a dispencer can give")