local OBJ = RDV.BF2_TURRET.AddVariant("Friendly")

OBJ:SetEnemyTeams({ -- TARGET SELECT PLAYER TEAMS
	TEAM_BOSK,
	TEAM_HONDO, 
	TEAM_CADBANE, 
	TEAM_PREVISZLA, 
	TEAM_SAVAGEOPRESS, 
	TEAM_GENERALGRIEVOUS, 
	TEAM_DARTHMAUL, 
	TEAM_ASAJJVENTRESS, 
	TEAM_COUNTDOOKU, 
	TEAM_CUSTOMENEMY, 
	TEAM_BXASSAULT, 
	TEAM_BXHEAVY, 
	TEAM_BXMARK, 
	TEAM_BXMELEE, 
	TEAM_BXCAPTAIN, 
	TEAM_DEATHWATCH, 
	TEAM_SITH, 
	TEAM_MAGNA, 
	TEAM_DROIDEKA, 
	TEAM_B2DROID, 
	TEAM_DROIDCOMMANDER, 
	TEAM_COMMANDODROID, 
	TEAM_B1SNIPER, 
	TEAM_B1PILOT, 
	TEAM_B1HEAVY, 
	TEAM_B1BATTLE, 
	TEAM_B1ENGINEER, 
	TEAM_UNDEAD, 
	TEAM_PRISONER, 
	TEAM_PIRATETROOPER, 
	TEAM_PIRATEHEAVY, 
	TEAM_PIRATESNIPER, 
	TEAM_PIRATESPECIALIST, 
	TEAM_PIRATEMELEE, 
	TEAM_PIRATEMEDIC, 
	TEAM_PIRATEENGINEER, 
	TEAM_UMBARANTROOPER, 
	TEAM_UMBARANHEAVYTROOPER, 
	TEAM_UMBARANSNIPER, 
	TEAM_UMBARANENGINEER, 
	TEAM_UMBARANOFFICER, 
	TEAM_DURGE, 
})

OBJ:SetEnemyVehicles({ -- TARGET SPECIFIC LFS VEHICLES
    "lunasflightschool_combineheli",
})

OBJ:SetDestructTime(60)

OBJ:SetEnemyNPCs({ -- TARGET SPECIFIC NPC's
    "npc_antlionguard",
	"npc_combine_s",
	"npc_helicopter",
	"npc_manhack",
	"antlion",
	"npc_drg_zombie",
	"npc_drg_headcrab",
})

OBJ:SetAttackDamage(10)

OBJ:Register()