local OBJ = RDV.BF2_TURRET.AddVariant("Friendly")

OBJ:SetEnemyTeams({ -- TARGET SELECT PLAYER TEAMS
	TEAM_BATTLEDROID,
	TEAM_CQBATTLEDROID,
	TEAM_ROCKETDROID,
	TEAM_HEAVYBATTLEDROID,
	TEAM_RECONBATTLEDROID,
	TEAM_ENGINEERDROID,
	TEAM_MEDICALDROID,
	TEAM_COMMANDERDROID,
	TEAM_SITH,
	TEAM_SUPERBATTLEDROID,
	TEAM_SUPERJUMPDROID,
	TEAM_DROIDEKA,
	TEAM_MAGNAGUARD,
	TEAM_TACTICALDROID,
	TEAM_TANKERDROID,
	TEAM_SNIPERDROID,
	TEAM_TECHNICALDROID,
	TEAM_BOUNTYHUNTERREINFORCE,
	TEAM_BXCOMMANDODROID,
	TEAM_BXASSASSINDROID,
	TEAM_BXFLAMERDROID,
	TEAM_BXSPLICERDROID,
	TEAM_BXRECONDROID,
	TEAM_BXHEAVYDROID,
	TEAM_BXCOMMANDERDROID,
	TEAM_UMBARANTROOPER,
	TEAM_UMBARANHEAVYTROOPER,
	TEAM_UMBARANSNIPER,
	TEAM_UMBARANENGINEER,
	TEAM_UMBARANOFFICER,
	TEAM_PRISONER,
	TEAM_UNDEAD,
	TEAM_CUSTOMENEMY,
	TEAM_COUNTDOOKU,
	TEAM_ASAJJVENTRESS,
	TEAM_DARTHMAUL,
	TEAM_GENERALGRIEVOUS,
	TEAM_SAVAGEOPRESS,
	TEAM_PREVISZLA,
	TEAM_CADBANE,
	TEAM_HONDO,
	TEAM_BOSK,
	TEAM_DURGE,
})

OBJ:SetEnemyVehicles({ -- TARGET SPECIFIC LFS VEHICLES
    "lunasflightschool_combineheli",
})

OBJ:SetDestructTime(60)

OBJ:SetEnemyNPCs({ -- TARGET SPECIFIC NPC's
    "npc_antlionguard",
	"npc_combine_s",
	"npc_helicopter",
	"npc_manhack",
	"antlion",
	"npc_drg_zombie",
	"npc_drg_headcrab",
})

OBJ:SetAttackDamage(20)

OBJ:Register()