if (SERVER) then
	JediGeneral = {"TEAM_JEDIGENERALADI", "TEAM_GMGENERALADI", "TEAM_JEDIGENERALSHAAK", "TEAM_CGGENERALSHAAK", "TEAM_JEDIGENERALAAYLA", "TEAM_327THGENERALAAYLA", "TEAM_JEDIGENERALKIT", "TEAM_RCGENERALKIT", "TEAM_JEDIGENERALPLO", "TEAM_WPGENERALPLO", "TEAM_JEDIGENERALTANO", "TEAM_501STGENERALTANO", "TEAM_JEDIGENERALWINDU", "TEAM_JEDIGENERALOBI", "TEAM_212THGENERALOBI", "TEAM_JEDIGENERALSKYWALKER", "TEAM_501STGENERALSKYWALKER", "TEAM_JEDIGRANDMASTER", "TEAM_GCGRANDMASTER", "TEAM_JEDIGENERALVOS", "TEAM_SHADOWGENERALVOS", "TEAM_JEDIGENERALLUMINARA", "TEAM_GCGENERALLUMINARA" }
	
	JediCouncil = {"TEAM_JEDICOUNCIL", "TEAM_501STJEDI", "TEAM_212THJEDI", "TEAM_327THJEDI"}
	for _, job in pairs(JediGeneral) do table.insert(JediCouncil, job) end

	JediSentinel = { "TEAM_JEDISENTINEL" }
	for _, job in pairs(JediCouncil) do table.insert(JediSentinel, job) end

	JediGuardian = { "TEAM_JEDIGUARDIAN" }
	for _, job in pairs(JediCouncil) do table.insert(JediGuardian, job) end

	JediConsular = { "TEAM_JEDICONSULAR" }
	for _, job in pairs(JediCouncil) do table.insert(JediConsular, job) end

	JediAll = {"TEAM_JEDIPADAWAN", "TEAM_JEDIKNIGHT", "TEAM_JEDICONSULAR", "TEAM_JEDIGUARDIAN", "TEAM_JEDISENTINEL"}
	for _, job in pairs(JediCouncil) do table.insert(JediAll, job) end
end