NCS_DEFCON.CONFIG = {
    languageSet = "en",
    command = "!defconconfig",
    m_command = "!defcons",
    savecommand = "!savedefconsoles",
    consolemodel = "models/props_wasteland/laundry_dryer002.mdl",
    prefixtext = "NCS-Defcons",
    changesounden = true,
    nobox = false,
    displaychanger = true,
    defaultdefcon = false,
    disablehuddead = true,
    changesound = "buttons/blip1.wav",
    prefixcolor = Color(255,0,0),
    adjustw = 0,
    adjusth = 0,
    defconList = {},
    camienabled = false,
    admins = {["superadmin"] = "World",},
}