RDV.COMMUNICATIONS.S_CFG = {
    menuCommand = "!rconfig",
    chatCommand = "/rcomms",
    disableTeamChat = true,
    haloEnabled = true,
    startMuted = false,
    consoleModel = "models/props_c17/furnitureStove001a.mdl",
    consoleHealthEnabled = true,
    consoleHealthValue = 500,
    passiveChannelCount = 3,
    HUDLocation = false,
    speakBindEnabled = false,
    speakBindValue = KEY_G,
    chatPrefix = "Comms",
    chatColor = Color(255,0,0),
    commandBlacklist = {},
    defaultChannel = false,
}