local function AddPlayerModel( name, model )

	list.Set( "PlayerOptionsModel", name, model )
	player_manager.AddValidModel( name, model )
	
end

AddPlayerModel( "[JLM] Young Jango Fett (Open Season)", 			      "models/jajoff/sps/jlmbase/characters/jango_young.mdl" )
AddPlayerModel( "[JLM] Young Boba Fett ", 			      "models/jajoff/sps/jlmbase/characters/boba_young.mdl" )
AddPlayerModel( "[JLM] Montross (Open Season)", 			      "models/jajoff/sps/jlmbase/characters/montrossyoung.mdl" )
AddPlayerModel( "[JLM] Jaster Mereel (Open Season)", 			      "models/jajoff/sps/jlmbase/characters/jastermereel.mdl" )
AddPlayerModel( "[JLM] True Mandalorian Trooper (Open Season)", 			      "models/jajoff/sps/jlmbase/characters/OS_Trooper.mdl" )
AddPlayerModel( "[JLM] Mandalorian Assasin ", 			      "models/jajoff/sps/jlmbase/characters/mw_assasin.mdl" )
AddPlayerModel( "[JLM] Deathwatch Trooper (Open Season)", 			      "models/jajoff/sps/jlmbase/characters/OSDW_trooper.mdl" )
AddPlayerModel( "[JLM] Deathwatch Trooper (Clone Wars)", 			      "models/jajoff/sps/jlmbase/characters/CWDW_trooper.mdl" )
AddPlayerModel( "[JLM] Deathwatch Female Trooper (Clone Wars)", 			      "models/jajoff/sps/jlmbase/characters/cwdwmaul_trooper_female.mdl" )
AddPlayerModel( "[JLM] Maul's Deathwatch Trooper (Clone Wars)", 			      "models/jajoff/sps/jlmbase/characters/CWDWMAUL_trooper.mdl" )
AddPlayerModel( "[JLM] Tor Vizsla )", 			      "models/jajoff/sps/jlmbase/characters/torvizsla.mdl" )
AddPlayerModel( "[JLM] Pre Vizsla ", 			      "models/jajoff/sps/jlmbase/characters/previzsla.mdl" )
AddPlayerModel( "[JLM] Bo Katan ", 			      "models/jajoff/sps/jlmbase/characters/bokatan.mdl" )
AddPlayerModel( "[JLM] Vhonte Tervho  ", 			      "models/jajoff/sps/jlmbase/characters/vhonte.mdl" )
AddPlayerModel( "[JLM] Kal Skirata", 			      "models/jajoff/sps/jlmbase/characters/kalskirata.mdl" )
AddPlayerModel( "[JLM] Walon Vau", 			      "models/jajoff/sps/jlmbase/characters/walonvau.mdl" )
AddPlayerModel( "[JLM] Will Knech", 			      "models/jajoff/sps/jlmbase/characters/villknech.mdl" )
AddPlayerModel( "[JLM] Schewe Kir", 			      "models/jajoff/sps/jlmbase/characters/schewekir.mdl" )
AddPlayerModel( "[JLM] Mandalorian Journeyman Protector", 			      "models/jajoff/sps/jlmbase/characters/journeymanprotector.mdl" )
AddPlayerModel( "[JLM] Hondo Karr", 			      "models/jajoff/sps/jlmbase/characters/hondokarr.mdl" )
AddPlayerModel( "[JLM] Deg Hayden", 			      "models/jajoff/sps/jlmbase/characters/deghayden.mdl" )
AddPlayerModel( "[JLM] Bardan Jusik", 			      "models/jajoff/sps/jlmbase/characters/bardanjusik.mdl" )
AddPlayerModel( "[JLM] Gar Saxon", 			      "models/jajoff/sps/jlmbase/characters/garsaxon.mdl" )
AddPlayerModel( "[JLM] Dar Vont", 			      "models/jajoff/sps/jlmbase/characters/darvont.mdl" )
AddPlayerModel( "[JLM] Gauwr Hapi", 			      "models/jajoff/sps/jlmbase/characters/gauwr.mdl" )
AddPlayerModel( "[JLM] Azal Vernau", 			      "models/jajoff/sps/jlmbase/characters/azal_vernau.mdl" )
AddPlayerModel( "[JLM] Wa Vernau", 			      "models/jajoff/sps/jlmbase/characters/wa_vernau.mdl" )
AddPlayerModel( "[JLM] Smorff Dou", 			      "models/jajoff/sps/jlmbase/characters/smorff.mdl" )
AddPlayerModel( "[JLM] Dinii Jorad", 			      "models/jajoff/sps/jlmbase/characters/diniijorad.mdl" )
AddPlayerModel( "[JLM] Jaron Langley", 			      "models/jajoff/sps/jlmbase/characters/jaron_langley.mdl" )
AddPlayerModel( "[JLM] Modular Mandalorian Foundling 01", 			      "models/jajoff/sps/jlmbase/characters/modular_foundling01.mdl" )
AddPlayerModel( "[JLM] Modular Mandalorian Foundling 02", 			      "models/jajoff/sps/jlmbase/characters/modular_foundling02.mdl" )
AddPlayerModel( "[JLM] Modular Mandalorian Foundling 03", 			      "models/jajoff/sps/jlmbase/characters/modular_foundling03.mdl" )
AddPlayerModel( "[JLM] Modular Mandalorian Instructor 01", 			      "models/jajoff/sps/jlmbase/characters/modular_instructor01.mdl" )
AddPlayerModel( "[JLM] Modular Mandalorian Instructor 02", 			      "models/jajoff/sps/jlmbase/characters/modular_instructor02.mdl" )
AddPlayerModel( "[JLM] Modular Mandalorian Instructor 03", 			      "models/jajoff/sps/jlmbase/characters/modular_instructor03.mdl" )
AddPlayerModel( "[JLM] Modular Mandalorian Female Foundling 01", 			      "models/jajoff/sps/jlmbase/characters/modular_foundling01_female.mdl" )
AddPlayerModel( "[JLM] Modular Mandalorian Female Foundling 02", 			      "models/jajoff/sps/jlmbase/characters/modular_foundling02_female.mdl" )
AddPlayerModel( "[JLM] Modular Mandalorian Female Foundling 03", 			      "models/jajoff/sps/jlmbase/characters/modular_foundling03_female.mdl" )

