--[[---------------------------------------------------------------------------
Group chats
---------------------------------------------------------------------------
Team chat for when you have a certain job.
e.g. with the default police group chat, police officers, chiefs and mayors can
talk to one another through /g or team chat.

HOW TO MAKE A GROUP CHAT:
Simple method:
GAMEMODE:AddGroupChat(List of team variables separated by comma)

Advanced method:
GAMEMODE:AddGroupChat(a function with ply as argument that returns whether a random player is in one chat group)
This is for people who know how to script Lua.

---------------------------------------------------------------------------]]
-- Example: GAMEMODE:AddGroupChat(TEAM_MOB, TEAM_GANG)
-- Example: GAMEMODE:AddGroupChat(function(ply) return ply:isCP() end)
GAMEMODE:AddGroupChat(TEAM_CT, TEAM_CTJDSGT, TEAM_CTDSGT, TEAM_CTMDSGT, TEAM_CTSDSGT, TEAM_FLEETCTI) -- CT GROUP CHAT

GAMEMODE:AddGroupChat(TEAM_501STGENERAL,TEAM_501STMCOMMANDER, TEAM_501STCOMMANDER, TEAM_501STEXECUTIVEOFFICER, TEAM_501STJUGGERNAUT, TEAM_501STLIEUTENANT, TEAM_501STSERGEANT, TEAM_501STTROOPER, TEAM_501STMAJOR, TEAM_501STSPECIALIST, TEAM_501STARC, TEAM_ARCALPHA501st, TEAM_501STMEDOFFICER, TEAM_501STMEDTROOPER, TEAM_501STJEDI, TEAM_501STGENERALSKYWALKER, TEAM_501STGENERALTANO, TEAM_FLEET501STHOO) -- 501st GROUP CHAT

GAMEMODE:AddGroupChat(TEAM_212THGENERAL,TEAM_212THMCOMMANDER, TEAM_212THCOMMANDER, TEAM_212THEXECUTIVEOFFICER, TEAM_212THLIEUTENANT, TEAM_212THSERGEANT, TEAM_212THTROOPER, TEAM_212THMAJOR, TEAM_212THHEAVYTROOPER, TEAM_212THSPECIALIST, TEAM_212THARC, TEAM_ARCALPHA212th, TEAM_212THMEDOFFICER, TEAM_212THMEDTROOPER, TEAM_212THJEDI, TEAM_212THGENERALOBI, TEAM_FLEET212THHOO) -- 212th GROUP CHAT

GAMEMODE:AddGroupChat(TEAM_GREENGENERAL, TEAM_GREENMCOMMANDER, TEAM_GREENCOMMANDER, TEAM_GREENEXECUTIVEOFFICER, TEAM_GREENMARKSMAN, TEAM_GREENRANGER, TEAM_GREENLIEUTENANT, TEAM_GREENSERGEANT, TEAM_GREENTROOPER, TEAM_GREENMAJOR, TEAM_GREENSPECIALIST, TEAM_GCARC, TEAM_ARCALPHAGC, TEAM_GREENMEDOFFICER, TEAM_GREENMEDTROOPER, TEAM_GCGRANDMASTER, TEAM_GCGENERALLUMINARA, TEAM_FLEETGCRO) -- GC GROUP CHAT

GAMEMODE:AddGroupChat(TEAM_CGGENERAL, TEAM_CGMCOMMANDER, TEAM_CGCOMMANDER, TEAM_CGEXECUTIVEOFFICER, TEAM_CGSERGEANT, TEAM_CGTROOPER, TEAM_CGMASSIF, TEAM_CGHANDLER, TEAM_CGRIOT, TEAM_CGMJR, TEAM_CGLIEUTENANT, TEAM_CGARC, TEAM_ARCALPHACG, TEAM_CGMEDOFFICER, TEAM_CGMEDTROOPER, TEAM_CGGENERALSHAAK, TEAM_CGQUICKRESPONSEFORCE) -- CG GROUP CHAT

GAMEMODE:AddGroupChat(TEAM_CEGENERAL, TEAM_CEMCOMMANDER, TEAM_CECOMMANDER, TEAM_CETROOPER, TEAM_CESPECIALIST, TEAM_CEEXECUTIVEOFFICER, TEAM_CECHIEF, TEAM_CESERGEANT, TEAM_CELIEUTENANT, TEAM_CEFAB, TEAM_CEARC, TEAM_ARCALPHACE, TEAM_CEMECHANIC, TEAM_CEMEDOFFICER, TEAM_CEMEDTROOPER, TEAM_327THJEDI, TEAM_327THGENERALAAYLA) -- CE GROUP CHAT

GAMEMODE:AddGroupChat(TEAM_GMGENERAL, TEAM_GMMCOMMANDER, TEAM_GMCOMMANDER, TEAM_GMEXECUTIVEOFFICER, TEAM_GMFLAMETROOPER, TEAM_GMKUTROOPER, TEAM_GMLIEUTENANT, TEAM_GMSERGEANT, TEAM_GMTROOPER, TEAM_GMMAJOR, TEAM_GMSPECIALIST, TEAM_GMARC, TEAM_ARCALPHAGM, TEAM_GMMEDOFFICER, TEAM_GMMEDTROOPER, TEAM_GMGENERALADI, TEAM_FLEETBO) -- GM GROUP CHAT

GAMEMODE:AddGroupChat(TEAM_WPGENERAL, TEAM_ARCMCOMMANDER, TEAM_ARCCOMMANDER, TEAM_ARCEXECUTIVEOFFICER, TEAM_ARCPATHFINDER, TEAM_ARCMAJOR, TEAM_ARCLIEUTENANT, TEAM_ARCSERGEANT, TEAM_ARCTROOPER, TEAM_FLEETDR, TEAM_WPARC, TEAM_ARCALPHAWP, TEAM_ARCMEDOFFICER, TEAM_ARCMEDTROOPER, TEAM_WPGENERALPLO, TEAM_FLEET104THRO) -- 104th GROUP CHAT

GAMEMODE:AddGroupChat(TEAM_WINGL, TEAM_WINGM) -- WING SQUADRON GROUP CHAT

GAMEMODE:AddGroupChat(TEAM_RCMCO, TEAM_RCBOSS, TEAM_RCFIXER, TEAM_RCSEV, TEAM_RCSCORCH, TEAM_RCHUNTER, TEAM_RCCROSSHAIR, TEAM_RCWRECKER, TEAM_RCTECH, TEAM_RCECHO, TEAM_RCNINER, TEAM_RCFI, TEAM_RCDARMAN, TEAM_RCATIN, TEAM_RCVALE, TEAM_RCRIGGS, TEAM_RCPLANK, TEAM_RCWITT, TEAM_RCHOPE, TEAM_RCAIWHA, TEAM_RCAQUILA, TEAM_RCION, TEAM_RCYAYAX, TEAM_RCGENERAL,TEAM_REPUBLICCOMMANDOSGT, TEAM_REPUBLICCOMMANDO, TEAM_RCCORR, TEAM_RCGENERALKIT) -- RC GROUP CHAT

GAMEMODE:AddGroupChat(TEAM_SDWGENERAL,TEAM_SDWMCO,TEAM_SDWCO,TEAM_SDWXO,TEAM_SDWMJR,TEAM_SDWOFF,TEAM_SDWSGT,TEAM_SDWTRP,TEAM_CVLD,TEAM_CVSPC,TEAM_CVTRP, TEAM_SHADOWGENERALVOS) -- Shadow CHAT

GAMEMODE:AddGroupChat(TEAM_FLEETRECRUIT,TEAM_FLEETMEMBER,TEAM_FLEETLIEUTENANT,TEAM_FLEETMEMBERSNR,TEAM_FLEETADMIRAL,TEAM_GRANDADMIRAL,TEAM_FLEET_IO,TEAM_FLEET_RDM,TEAM_FLEET_RDE) -- FLEET CHAT

GAMEMODE:AddGroupChat(TEAM_JEDICOUNCIL, TEAM_JEDIKNIGHT, TEAM_JEDIPADAWAN, TEAM_JEDIGRANDMASTER, TEAM_JEDIGENERALTANO, TEAM_JEDIGENERALSKYWALKER, TEAM_JEDIGENERALOBI, TEAM_JEDIGENERALSHAAK, TEAM_JEDIGENERALAAYLA, TEAM_JEDIGENERALKIT, TEAM_JEDIGENERALPLO, TEAM_JEDIGENERALADI, TEAM_JEDIGENERALLUMINARA, TEAM_JEDIGENERALWINDU, TEAM_JEDIGUARDIAN, TEAM_JEDICONSULAR, TEAM_JEDISENTINEL, TEAM_JEDIGENERALVOS, TEAM_JEDIYOUNGLING, TEAM_JEDISHADOW, TEAM_JEDIHEALER, TEAM_JEDITOURNAMENT, TEAM_JEDICONGUARD, TEAM_JEDISENGUARD, TEAM_JEDIGUARGUARD, TEAM_JEDIGURDCHIEF) -- JEDI GROUP CHAT

GAMEMODE:AddGroupChat(TEAM_SOD, TEAM_SITH, TEAM_EE, TEAM_BATTLEDROID, TEAM_ROCKETDROID, TEAM_HEAVYBATTLEDROID, TEAM_RECONBATTLEDROID, TEAM_ENGINEERDROID, TEAM_MEDICALDROID, TEAM_COMMANDERDROID, TEAM_SUPERBATTLEDROID, TEAM_SUPERJUMPDROID, TEAM_TACTICALDROID, TEAM_SNIPERDROID, TEAM_TECHNICALDROID, TEAM_BXCOMMANDODROID, TEAM_BXSLUGDROID, TEAM_BXSPLICERDROID, TEAM_BXRECONDROID, TEAM_BXHEAVYDROID, TEAM_BXCOMMANDERDROID, TEAM_BXASSASSINDROID, TEAM_BOUNTYHUNTERREINFORCE, TEAM_TANKERDROID, TEAM_MAGNAGUARD, TEAM_CQBATTLEDROID, TEAM_B1BATTLE, TEAM_B1HEAVY, TEAM_B1SNIPER, TEAM_B2DROID, TEAM_COMMANDODROID, TEAM_MAGNA, TEAM_CUSTOMENEMY, TEAM_DEATHWATCH, TEAM_COUNTDOOKU, TEAM_ASAJJVENTRESS, TEAM_GENERALGRIEVOUS, TEAM_SAVAGEOPRESS, TEAM_PREVISZLA, TEAM_CADBANE, TEAM_HONDO, TEAM_DARTHMAUL, TEAM_BOSK, TEAM_DROIDCOMMANDER, TEAM_BXCAPTAIN, TEAM_BXMELEE, TEAM_BXMARK, TEAM_BXASSAULT, TEAM_B1PILOT, TEAM_GARSAXON, TEAM_ENEMYENGINEER, TEAM_PIRATETROOPER, TEAM_PIRATEHEAVY, TEAM_PIRATESNIPER, TEAM_PIRATESPECIALIST, TEAM_PIRATEMELEE, TEAM_PIRATEMEDIC, TEAM_PIRATEENGINEER, TEAM_UMBARANTROOPER, TEAM_UMBARANHEAVYTROOPER, TEAM_UMBARANSNIPER, TEAM_UMBARANENGINEER, TEAM_UMBARANOFFICER, TEAM_EH, TEAM_PRISONER, TEAM_CISSIMBOM, TEAM_UNDEAD, TEAM_REPUBLICCHARACTER) -- Staff / Event enemy Group Chat
GAMEMODE:AddGroupChat(TEAM_SIMJET, TEAM_SIMPILOT, TEAM_SIMMEDIC, TEAM_SIMSNIPER, TEAM_SIMHEAVY, TEAM_SIMRBOMBER, TEAM_SIMASSAULT) -- Simulation
GAMEMODE:AddGroupChat(TEAM_ARCMC, TEAM_ARCCOLT, TEAM_ARCHAVOC, TEAM_TRAINEEARC, TEAM_ARCGENERAL) -- ARC Commanders
GAMEMODE:AddGroupChat(TEAM_MEDICALMCO, TEAM_MEDICALDIRECTOR, TEAM_FLEETMO, TEAM_MEDICALGENERAL, TEAM_ASSISTANTMEDICALDIRECTOR) -- Medical directive
GAMEMODE:AddGroupChat(TEAM_BATTALIONGENERAL, TEAM_ASSISTANTBATTALIONGENERAL, TEAM_SUPREMEGENERAL, TEAM_NSOCPT, TEAM_NSOADV, TEAM_NSOA, TEAM_NSOMED, TEAM_NSOCQC) -- Republic Generals
GAMEMODE:AddGroupChat(TEAM_DUA, TEAM_SIEGE, TEAM_MEDMM, TEAM_JAGUAR) -- Clone Reinforcement
--DarkRP.createGroupChat(function(ply) return ply:isCP() end)
DarkRP.createGroupChat(TEAM_MOB, TEAM_GANG)
DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
-- Initial team when first spawning
GAMEMODE.DefaultTeam = TEAM_CADET